[package]
name = "bevy_remote"
version = "0.15.0-dev"
edition = "2021"
description = "The Bevy Remote Protocol"
homepage = "https://bevyengine.org"
repository = "https://github.com/bevyengine/bevy"
license = "MIT OR Apache-2.0"
keywords = ["bevy"]

[features]
default = ["http"]
http = ["dep:async-io", "dep:smol-hyper"]

[dependencies]
# bevy
bevy_app = "0.15"
bevy_derive = "0.15"
bevy_ecs = { version = "0.15", features = ["serialize"] }
bevy_hierarchy = { version = "0.15" }
bevy_reflect = { version = "0.15" }
bevy_tasks = { version = "0.15" }
bevy_utils = { version = "0.15" }

# other
anyhow = "1"
hyper = { version = "1", features = ["server", "http1"] }
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1" }
http-body-util = "0.1"
async-channel = "2"

# dependencies that will not compile on wasm
[target.'cfg(not(target_family = "wasm"))'.dependencies]
async-io = { version = "2", optional = true }
smol-hyper = { version = "0.1", optional = true }

[lints]
workspace = true

[package.metadata.docs.rs]
rustdoc-args = ["-Zunstable-options", "--cfg", "docsrs"]
all-features = true
